Challenge
sisyphusprotocol/contracts pull request #1
Opened 2022-10-27 05:20 UTC by xiaoZ857

2022-10-27 18:27 UTC, noyyyy requested changes

2022-10-27 18:27 UTC, noyyyy commented on contracts/Campaign.sol
> +
why cheatCount += 1

2022-10-27 18:28 UTC, noyyyy commented
run `git pull origin main --rebase` to fetch the newest change from main.

2022-10-29 15:52 UTC, xiaoZ857 commented on contracts/Campaign.sol
> +    require(_legal == true, 'Challenge: not enough voter');
solved

2022-10-29 15:55 UTC, xiaoZ857 commented on contracts/Campaign.sol
> +      IERC20(targetToken).safeTransfer(Consts.PROTOCOL_RECIPIENT, _tranReward/10);
solved

2022-10-30 07:15 UTC, xiaoZ857 commented on contracts/Campaign.sol
> +    }
solved

2022-10-30 07:15 UTC, xiaoZ857 commented on contracts/Campaign.sol
> +      emit EvFailure(_cheaterId);
solved by adding a event of cheatment

2022-10-30 07:16 UTC, xiaoZ857 commented on contracts/Campaign.sol
> +
solved

2022-10-30 08:54 UTC, merged